pull_request_rules:
  - name: Squash and merge (one commit)
    conditions:
      - check-success="Tests (windows-latest)"
      - check-success="Tests (macos-latest)"
      - check-success="Tests (ubuntu-24.04)"
      - check-success=Mypy
      - "#commits=1"
      - or:
        - "#approved-reviews-by>0"
        - author=Kicer86
    actions:
      merge:
        method: squash
      delete_head_branch:
        force: false

  - name: Merge pull request (more than one commit)
    conditions:
      - check-success="Tests (windows-latest)"
      - check-success="Tests (macos-latest)"
      - check-success="Tests (ubuntu-24.04)"
      - check-success=Mypy
      - "#commits>1"
      - "#commits-behind=0"
      - or:
        - "#approved-reviews-by>0"
        - author=Kicer86
    actions:
      merge:
        method: merge
      delete_head_branch:
        force: false
