"""Generate completion once so pressing Tab never starts the Python CLI."""

import argparse
import shlex
from collections.abc import Iterator, Sequence


_ROOT_CONTEXT = "root"


def _context_name(path: tuple[str, ...]) -> str:
    return "__".join(path) if path else _ROOT_CONTEXT


def _walk_parsers(
    parser: argparse.ArgumentParser,
    path: tuple[str, ...] = (),
) -> Iterator[tuple[tuple[str, ...], argparse.ArgumentParser]]:
    yield path, parser
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            for command, subparser in action.choices.items():
                yield from _walk_parsers(subparser, (*path, command))


def _subcommands(parser: argparse.ArgumentParser) -> tuple[str, ...]:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return tuple(action.choices)
    return ()


def _option_actions(parser: argparse.ArgumentParser) -> Iterator[argparse.Action]:
    return (action for action in parser._actions if action.option_strings)


def _case_patterns(context: str, options: Sequence[str]) -> str:
    return "|".join(f"{context}:{option}" for option in options)


def _word_list(values: tuple[object, ...] | list[str]) -> str:
    return shlex.quote(" ".join(str(value) for value in values))


def build_bash_completion(parser: argparse.ArgumentParser) -> str:
    """Build a self-contained Bash completion script from an argparse tree."""
    contexts = list(_walk_parsers(parser))
    lines = [
        "# Generated by `twotone --install-completion`; do not edit.",
        "_twotone_complete_words()",
        "{",
        "    local candidate",
        "    COMPREPLY=()",
        '    while IFS= read -r candidate; do COMPREPLY+=("$candidate"); done < <(compgen -W "$1" -- "$2")',
        "}",
        "",
        "_twotone_complete_files()",
        "{",
        "    local candidate",
        "    COMPREPLY=()",
        "    compopt -o filenames",
        '    while IFS= read -r candidate; do COMPREPLY+=("$candidate"); done < <(compgen -f -- "$1")',
        "}",
        "",
        "_twotone_complete()",
        "{",
        "    local cur prev context word index skip_next",
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        '    prev=""',
        '    (( COMP_CWORD > 0 )) && prev="${COMP_WORDS[COMP_CWORD - 1]}"',
        f"    context={_ROOT_CONTEXT}",
        "    skip_next=0",
        "",
        "    for (( index=1; index<COMP_CWORD; index++ )); do",
        '        word="${COMP_WORDS[index]}"',
        "        if (( skip_next )); then",
        "            skip_next=0",
        "            continue",
        "        fi",
        "",
        '        case "$context:$word" in',
    ]

    for path, context_parser in contexts:
        context = _context_name(path)
        value_options = [
            option
            for action in _option_actions(context_parser)
            if action.nargs != 0
            for option in action.option_strings
        ]
        if value_options:
            patterns = _case_patterns(context, value_options)
            lines.append(f"            {patterns}) skip_next=1 ;;")

        for command in _subcommands(context_parser):
            child_context = _context_name((*path, command))
            lines.append(f"            {context}:{command}) context={child_context} ;;")

    lines.extend([
        "        esac",
        "    done",
        "",
        '    case "$context:$prev" in',
    ])

    for path, context_parser in contexts:
        context = _context_name(path)
        for action in _option_actions(context_parser):
            if action.nargs == 0:
                continue
            patterns = _case_patterns(context, action.option_strings)
            if action.choices is not None:
                values = tuple(action.choices)
                lines.extend([
                    f"        {patterns})",
                    f"            _twotone_complete_words {_word_list(values)} \"$cur\"",
                    "            return",
                    "            ;;",
                ])
            else:
                lines.extend([
                    f"        {patterns})",
                    '            _twotone_complete_files "$cur"',
                    "            return",
                    "            ;;",
                ])

    lines.extend([
        "    esac",
        "",
        '    if [[ "$cur" == -* ]]; then',
        '        case "$context" in',
    ])

    for path, context_parser in contexts:
        context = _context_name(path)
        options = [
            option
            for action in _option_actions(context_parser)
            for option in action.option_strings
        ]
        lines.extend([
            f"            {context})",
            f"                _twotone_complete_words {_word_list(options)} \"$cur\"",
            "                return",
            "                ;;",
        ])

    lines.extend([
        "        esac",
        "    fi",
        "",
        '    case "$context" in',
    ])

    for path, context_parser in contexts:
        commands = _subcommands(context_parser)
        if not commands:
            continue
        context = _context_name(path)
        lines.extend([
            f"        {context})",
            f"            _twotone_complete_words {_word_list(commands)} \"$cur\"",
            "            ;;",
        ])

    lines.extend([
        "        *)",
        '            _twotone_complete_files "$cur"',
        "            ;;",
        "    esac",
        "}",
        "",
        "complete -F _twotone_complete twotone",
        "",
    ])
    return "\n".join(lines)
