
name: Linux-mypy

on:
  push:
    branches:
      - master
    paths:
      - 'twotone/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'mypy.ini'
      - '.github/workflows/mypy.yml'
      - '.github/actions/**'
  pull_request:
    paths:
      - 'twotone/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'mypy.ini'
      - '.github/workflows/mypy.yml'
      - '.github/actions/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  mypy:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true

    - name: Set up Python environment
      uses: ./.github/actions/setup-python-project
      with:
        python-version: '3.12'
        extra-packages: mypy scipy-stubs types-requests types-tqdm

    - name: Run mypy
      run: python -m mypy twotone tests
