
name: unittests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "requirements.txt"

    - name: Install required tools (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update && \
        sudo apt-get install -y \
          exiftool \
          ffmpeg \
          mkvtoolnix

    - name: Install required tools (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update && \
        brew install exiftool ffmpeg mkvtoolnix

    - name: Install required tools (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install -y exiftool ffmpeg mkvtoolnix
        refreshenv

    - name: Run unit tests
      run: |
        python -m unittest discover tests
